### ISSUE TITLE
bug (gradio-pdf): preview not displaying CJK characters

### ISSUE THREAD

**Issue by tastelikefeet** [Byaidu/PDFMathTranslate#273]
## 问题描述
请对问题进行描述，并提供日志或截图
请确认 issues 中没有相同问题且完整阅读 wiki
**本项目不处理网络环境引发的问题**（例如 empty translation result/connection reset/check_hostname requires server_hostname/certificate verify failed/unable to connect to proxy/LocalEntryNotFoundError）

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档

1. gradio翻译完成后预览效果不正常

![image](https://github.com/user-attachments/assets/110198af-29dd-4be3-8707-2178cfe1aff1)

2. gradio在国内如果选择连接不通的translater会等待很长时间，影响使用，建议增加并发或者减少retry

**Comment by hellofinch** [comment]
gradio翻译完成后预览效果不正常是因为没有获取到cmap的文件，可能需要向上游gradio-pdf反馈。

**Comment by awwaawwa** [comment]
第二点我写 https://github.com/Byaidu/PDFMathTranslate/issues/216#issuecomment-2543347690 的时候看看

**Comment by reycn** [comment]
If necessary, rollback to my image preview, lol

**Comment by Byaidu** [comment]
其实还好，这个文字显示也不是大问题

**Comment by reycn** [comment]
The bug in upstream has been fixed at in its [PR#34](https://github.com/freddyaboulton/gradio-pdf/pull/34), which has been released as `v0.0.21`.

I am working on it.

**Comment by reycn** [comment]
This bug has been fixed in [CMT#b9ae66bd59fde45d3b52d499611cda4b5fb83466](https://github.com/Byaidu/PDFMathTranslate/commit/b9ae66bd59fde45d3b52d499611cda4b5fb83466).

With the following different results before & after the present fix:

- Before, `gradio-pdf<0.0..21`
<img width="1253" alt="21" src="https://github.com/user-attachments/assets/cae803fc-e8a8-4b4e-9e41-ff05812c501d" />

- After, `gradio-pdf>0.0.21`
<img width="1256" alt="= 21" src="https://github.com/user-attachments/assets/ddac9a62-e4a9-4d23-aaaf-570cbd4e246e" />
